USE [GuestHouse];
GO

-- ==============================================================================
-- 1. Ensure Hotel Exists (Kalika Hotel & Lodge, Itahari-9, Buspark)
-- ==============================================================================
IF NOT EXISTS (SELECT 1 FROM [hotel] WHERE [hotel_id] = 1)
BEGIN
    SET IDENTITY_INSERT [hotel] ON;
    INSERT INTO [hotel] ([hotel_id], [name], [address], [phone], [email], [website_url], [created_at])
    VALUES (1, 'Kalika Hotel & Lodge', 'Itahari-9, Buspark', '9800000000', 'kalika.itahari@gmail.com', 'https://kalikahotel.com', GETDATE());
    SET IDENTITY_INSERT [hotel] OFF;
END
GO

-- ==============================================================================
-- 2. Ensure Required Roles Exist (Admin, Guest, Staff)
-- ==============================================================================
IF NOT EXISTS (SELECT 1 FROM [role] WHERE [role_name] = 'Admin')
    INSERT INTO [role] ([role_name], [description]) VALUES ('Admin', 'Full administrative access');

IF NOT EXISTS (SELECT 1 FROM [role] WHERE [role_name] = 'Guest')
    INSERT INTO [role] ([role_name], [description]) VALUES ('Guest', 'Hotel guest account');

IF NOT EXISTS (SELECT 1 FROM [role] WHERE [role_name] = 'Staff')
    INSERT INTO [role] ([role_name], [description]) VALUES ('Staff', 'General staff member');
GO

-- ==============================================================================
-- 3. Insert Test Staff Users with Exact PBKDF2 Hashed Passwords
-- ==============================================================================
DECLARE @HotelId INT = (SELECT TOP 1 [hotel_id] FROM [hotel] ORDER BY [hotel_id]);
DECLARE @AdminRoleId INT = (SELECT [role_id] FROM [role] WHERE [role_name] = 'Admin');
DECLARE @GuestRoleId INT = (SELECT [role_id] FROM [role] WHERE [role_name] = 'Guest');
DECLARE @StaffRoleId INT = (SELECT [role_id] FROM [role] WHERE [role_name] = 'Staff');

-- Pre-computed hashes generated by PasswordService (PBKDF2 SHA-256 with 100,000 iterations):
-- Password: Admin@123
DECLARE @AdminHash NVARCHAR(255) = 'oByNQe0IdymBbpdqYtl1bg==:kC46RnwB5IwQf9OWzKopvow57XXUWpYRuuK+n7dStkg=:100000';

-- Password: Guest@123
DECLARE @GuestHash NVARCHAR(255) = '5YXwG49Cy1Ic8OiAjls/Jw==:vs2joFGURRc6XOD1qKbsF/nWa7RmqrZ2vXPXide73Mk=:100000';

-- Password: Staff@123
DECLARE @StaffHash NVARCHAR(255) = 'fKs7TRPZfk/Gwp2aM4jt0g==:odOVUHX48bqV8DNSqGyzf3hCk94tq5FfzPvenxo62Pk=:100000';

-- Password: Inactive@123 (for testing inactive account validation)
DECLARE @InactiveHash NVARCHAR(255) = '+TkeGLW68d7Q6iSHLN6YZQ==:LoMwNG5vjgAEnqVhag11x/VoxoUb8nkIZys0ih8T5vI=:100000';

-- A. Admin User (admin@gmail.com / Admin@123)
IF NOT EXISTS (SELECT 1 FROM [staff_user] WHERE [username] = 'admin@gmail.com')
BEGIN
    INSERT INTO [staff_user] ([hotel_id], [role_id], [full_name], [username], [password_hash], [is_active], [created_at], [updated_at])
    VALUES (@HotelId, @AdminRoleId, 'Test Admin', 'admin@gmail.com', @AdminHash, 1, GETDATE(), GETDATE());
END

-- B. Guest User (guest@gmail.com / Guest@123)
IF NOT EXISTS (SELECT 1 FROM [staff_user] WHERE [username] = 'guest@gmail.com')
BEGIN
    INSERT INTO [staff_user] ([hotel_id], [role_id], [full_name], [username], [password_hash], [is_active], [created_at], [updated_at])
    VALUES (@HotelId, @GuestRoleId, 'Test Guest', 'guest@gmail.com', @GuestHash, 1, GETDATE(), GETDATE());
END

-- C. Staff User (staff@gmail.com / Staff@123)
IF NOT EXISTS (SELECT 1 FROM [staff_user] WHERE [username] = 'staff@gmail.com')
BEGIN
    INSERT INTO [staff_user] ([hotel_id], [role_id], [full_name], [username], [password_hash], [is_active], [created_at], [updated_at])
    VALUES (@HotelId, @StaffRoleId, 'Test Staff', 'staff@gmail.com', @StaffHash, 1, GETDATE(), GETDATE());
END

-- D. Inactive User (inactive@gmail.com / Inactive@123)
IF NOT EXISTS (SELECT 1 FROM [staff_user] WHERE [username] = 'inactive@gmail.com')
BEGIN
    INSERT INTO [staff_user] ([hotel_id], [role_id], [full_name], [username], [password_hash], [is_active], [created_at], [updated_at])
    VALUES (@HotelId, @StaffRoleId, 'Test Inactive User', 'inactive@gmail.com', @InactiveHash, 0, GETDATE(), GETDATE());
END
GO
