// <auto-generated />
using System;
using Guest_House.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Guest_House.Migrations
{
    [DbContext(typeof(GuestHouseContext))]
    [Migration("20260927032643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Guest_House.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("confirmed");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("ExpectedCheckout")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("BookingId")
                        .HasName("PK__booking__5DE3A5B1A1852AEF");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Guest_House.Models.BookingRoom", b =>
                {
                    b.Property<int>("BookingRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingRoomId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfGuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("RoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingRoomId")
                        .HasName("PK__booking___083C323CF8FCDD25");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("BookingRooms");
                });

            modelBuilder.Entity("Guest_House.Models.ExpenseCharge", b =>
                {
                    b.Property<int>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("charge_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChargeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("charge_type");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("IncurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("incurred_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("RoomOrderId")
                        .HasColumnType("int")
                        .HasColumnName("room_order_id");

                    b.Property<int>("StayId")
                        .HasColumnType("int")
                        .HasColumnName("stay_id");

                    b.HasKey("ChargeId")
                        .HasName("PK__expense___F3F52EBC8523040C");

                    b.HasIndex("RoomOrderId");

                    b.HasIndex("StayId");

                    b.ToTable("expense_charge");
                });

            modelBuilder.Entity("Guest_House.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProofNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProofType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("GuestId")
                        .HasName("PK__guest__19778E35E72EB441");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Guest_House.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website_url");

                    b.HasKey("HotelId")
                        .HasName("PK__hotel__45FE7E26B6AB96C7");

                    b.ToTable("hotel");
                });

            modelBuilder.Entity("Guest_House.Models.HotelExpense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("expense_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ExpenseCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("expense_category");

                    b.Property<DateTime?>("ExpenseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("expense_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("receipt_url");

                    b.HasKey("ExpenseId")
                        .HasName("PK__hotel_ex__404B6A6B6241CB8E");

                    b.HasIndex("HotelId");

                    b.ToTable("hotel_expense");
                });

            modelBuilder.Entity("Guest_House.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("due_amount");

                    b.Property<decimal>("ExtraChargeTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("extra_charge_total");

                    b.Property<DateTime?>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("grand_total");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("unpaid")
                        .HasColumnName("invoice_status");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("paid_amount");

                    b.Property<decimal>("RoomChargeTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("room_charge_total");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("tax_amount");

                    b.HasKey("InvoiceId")
                        .HasName("PK__invoice__F58DFD498E7AFB15");

                    b.HasIndex(new[] { "BookingId" }, "UQ_invoice_booking")
                        .IsUnique();

                    b.HasIndex(new[] { "InvoiceNumber" }, "UQ_invoice_number")
                        .IsUnique();

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("Guest_House.Models.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("item_type");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("InvoiceItemId")
                        .HasName("PK__invoice___84ECDEE94302E4E3");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_item");
                });

            modelBuilder.Entity("Guest_House.Models.MenuCategory", b =>
                {
                    b.Property<int>("MenuCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("menu_category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.HasKey("MenuCategoryId")
                        .HasName("PK__menu_cat__E3FCE267B00BEA9A");

                    b.HasIndex(new[] { "HotelId", "CategoryName" }, "UQ_menu_category_hotel_name")
                        .IsUnique();

                    b.ToTable("menu_category");
                });

            modelBuilder.Entity("Guest_House.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("menu_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("item_name");

                    b.Property<int>("MenuCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("menu_category_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("MenuItemId")
                        .HasName("PK__menu_ite__973431D5E3BF0586");

                    b.HasIndex("MenuCategoryId");

                    b.ToTable("menu_item");
                });

            modelBuilder.Entity("Guest_House.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("payment_status");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_type");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_ref");

                    b.HasKey("PaymentId")
                        .HasName("PK__payment__ED1FC9EAE8DCF960");

                    b.HasIndex("BookingId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("Guest_House.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__role__760965CC2BE7F92A");

                    b.HasIndex(new[] { "RoleName" }, "UQ_role_name")
                        .IsUnique();

                    b.ToTable("role");
                });

            modelBuilder.Entity("Guest_House.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("floor_number");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("room_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("available")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("RoomId")
                        .HasName("PK__room__19675A8A4B774315");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "HotelId", "RoomNumber" }, "UQ_room_hotel_number")
                        .IsUnique();

                    b.ToTable("room");
                });

            modelBuilder.Entity("Guest_House.Models.RoomCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("base_price");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<int>("MaxOccupancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_occupancy");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("CategoryId")
                        .HasName("PK__room_cat__D54EE9B48EAB7E99");

                    b.HasIndex(new[] { "HotelId", "CategoryName" }, "UQ_room_category_hotel_name")
                        .IsUnique();

                    b.ToTable("room_category");
                });

            modelBuilder.Entity("Guest_House.Models.RoomMedium", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("caption");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("media_type");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("MediaId")
                        .HasName("PK__room_med__D0A840F42C338844");

                    b.HasIndex("RoomId");

                    b.ToTable("room_media");
                });

            modelBuilder.Entity("Guest_House.Models.RoomOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("order_status");

                    b.Property<DateTime?>("OrderedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ordered_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int>("StayId")
                        .HasColumnType("int")
                        .HasColumnName("stay_id");

                    b.HasKey("OrderId")
                        .HasName("PK__room_ord__4659622966EB661B");

                    b.HasIndex("RoomId");

                    b.HasIndex("StayId");

                    b.HasIndex(new[] { "OrderNumber" }, "UQ_room_order_number")
                        .IsUnique();

                    b.ToTable("room_order");
                });

            modelBuilder.Entity("Guest_House.Models.RoomOrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<string>("SpecialInstruction")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("special_instruction");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderItemId")
                        .HasName("PK__room_ord__3764B6BC38D39CEE");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("room_order_item");
                });

            modelBuilder.Entity("Guest_House.Models.StaffUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__staff_us__B9BE370F5FAF11F2");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ_staff_user_username")
                        .IsUnique();

                    b.ToTable("staff_user");
                });

            modelBuilder.Entity("Guest_House.Models.Stay", b =>
                {
                    b.Property<int>("StayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stay_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StayId"));

                    b.Property<DateTime?>("ActualCheckin")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_checkin");

                    b.Property<DateTime?>("ActualCheckout")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_checkout");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("StayStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("stay_status");

                    b.HasKey("StayId")
                        .HasName("PK__stay__C2B9B01F6D8F79C1");

                    b.HasIndex(new[] { "BookingId" }, "UQ_stay_booking")
                        .IsUnique();

                    b.ToTable("stay");
                });

            modelBuilder.Entity("Guest_House.Models.WebsiteSyncLog", b =>
                {
                    b.Property<int>("SyncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sync_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SyncId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("error_message");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("success")
                        .HasColumnName("sync_status");

                    b.Property<DateTime?>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("SyncId")
                        .HasName("PK__website___54E41ED0AF405D67");

                    b.HasIndex("HotelId");

                    b.ToTable("website_sync_log");
                });

            modelBuilder.Entity("Guest_House.Models.Booking", b =>
                {
                    b.HasOne("Guest_House.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .IsRequired()
                        .HasConstraintName("FK_booking_guest");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Guest_House.Models.BookingRoom", b =>
                {
                    b.HasOne("Guest_House.Models.Booking", "Booking")
                        .WithMany("BookingRooms")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_booking_room_booking");

                    b.HasOne("Guest_House.Models.Room", "Room")
                        .WithMany("BookingRooms")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_booking_room_room");

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Guest_House.Models.ExpenseCharge", b =>
                {
                    b.HasOne("Guest_House.Models.RoomOrder", "RoomOrder")
                        .WithMany("ExpenseCharges")
                        .HasForeignKey("RoomOrderId")
                        .HasConstraintName("FK_expense_charge_room_order");

                    b.HasOne("Guest_House.Models.Stay", "Stay")
                        .WithMany("ExpenseCharges")
                        .HasForeignKey("StayId")
                        .IsRequired()
                        .HasConstraintName("FK_expense_charge_stay");

                    b.Navigation("RoomOrder");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Guest_House.Models.HotelExpense", b =>
                {
                    b.HasOne("Guest_House.Models.Hotel", "Hotel")
                        .WithMany("HotelExpenses")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_hotel_expense_hotel");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Guest_House.Models.Invoice", b =>
                {
                    b.HasOne("Guest_House.Models.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("Guest_House.Models.Invoice", "BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_invoice_booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Guest_House.Models.InvoiceItem", b =>
                {
                    b.HasOne("Guest_House.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_invoice_item_invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Guest_House.Models.MenuCategory", b =>
                {
                    b.HasOne("Guest_House.Models.Hotel", "Hotel")
                        .WithMany("MenuCategories")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_menu_category_hotel");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Guest_House.Models.MenuItem", b =>
                {
                    b.HasOne("Guest_House.Models.MenuCategory", "MenuCategory")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_menu_item_category");

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("Guest_House.Models.Payment", b =>
                {
                    b.HasOne("Guest_House.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_payment_booking");

                    b.HasOne("Guest_House.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("FK_payment_invoice");

                    b.Navigation("Booking");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Guest_House.Models.Room", b =>
                {
                    b.HasOne("Guest_House.Models.RoomCategory", "Category")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_room_category");

                    b.HasOne("Guest_House.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_room_hotel");

                    b.Navigation("Category");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Guest_House.Models.RoomCategory", b =>
                {
                    b.HasOne("Guest_House.Models.Hotel", "Hotel")
                        .WithMany("RoomCategories")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_room_category_hotel");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Guest_House.Models.RoomMedium", b =>
                {
                    b.HasOne("Guest_House.Models.Room", "Room")
                        .WithMany("RoomMedia")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_room_media_room");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Guest_House.Models.RoomOrder", b =>
                {
                    b.HasOne("Guest_House.Models.Room", "Room")
                        .WithMany("RoomOrders")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_room_order_room");

                    b.HasOne("Guest_House.Models.Stay", "Stay")
                        .WithMany("RoomOrders")
                        .HasForeignKey("StayId")
                        .IsRequired()
                        .HasConstraintName("FK_room_order_stay");

                    b.Navigation("Room");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Guest_House.Models.RoomOrderItem", b =>
                {
                    b.HasOne("Guest_House.Models.MenuItem", "MenuItem")
                        .WithMany("RoomOrderItems")
                        .HasForeignKey("MenuItemId")
                        .IsRequired()
                        .HasConstraintName("FK_room_order_item_menu");

                    b.HasOne("Guest_House.Models.RoomOrder", "Order")
                        .WithMany("RoomOrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_room_order_item_order");

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Guest_House.Models.StaffUser", b =>
                {
                    b.HasOne("Guest_House.Models.Hotel", "Hotel")
                        .WithMany("StaffUsers")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_staff_user_hotel");

                    b.HasOne("Guest_House.Models.Role", "Role")
                        .WithMany("StaffUsers")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_staff_user_role");

                    b.Navigation("Hotel");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Guest_House.Models.Stay", b =>
                {
                    b.HasOne("Guest_House.Models.Booking", "Booking")
                        .WithOne("Stay")
                        .HasForeignKey("Guest_House.Models.Stay", "BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_stay_booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Guest_House.Models.WebsiteSyncLog", b =>
                {
                    b.HasOne("Guest_House.Models.Hotel", "Hotel")
                        .WithMany("WebsiteSyncLogs")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_website_sync_log_hotel");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Guest_House.Models.Booking", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("Invoice");

                    b.Navigation("Payments");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Guest_House.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Guest_House.Models.Hotel", b =>
                {
                    b.Navigation("HotelExpenses");

                    b.Navigation("MenuCategories");

                    b.Navigation("RoomCategories");

                    b.Navigation("Rooms");

                    b.Navigation("StaffUsers");

                    b.Navigation("WebsiteSyncLogs");
                });

            modelBuilder.Entity("Guest_House.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Guest_House.Models.MenuCategory", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Guest_House.Models.MenuItem", b =>
                {
                    b.Navigation("RoomOrderItems");
                });

            modelBuilder.Entity("Guest_House.Models.Role", b =>
                {
                    b.Navigation("StaffUsers");
                });

            modelBuilder.Entity("Guest_House.Models.Room", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("RoomMedia");

                    b.Navigation("RoomOrders");
                });

            modelBuilder.Entity("Guest_House.Models.RoomCategory", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Guest_House.Models.RoomOrder", b =>
                {
                    b.Navigation("ExpenseCharges");

                    b.Navigation("RoomOrderItems");
                });

            modelBuilder.Entity("Guest_House.Models.Stay", b =>
                {
                    b.Navigation("ExpenseCharges");

                    b.Navigation("RoomOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
